baseURL: "https://coderrenxy.github.io/"
title: 小任同学's Blog
languageCode: zh-cn # en-us
theme: PaperMod # 主题名字，和themes文件夹下的一致

enableInlineShortcodes: true
enableEmoji: true # 允许使用 Emoji 表情，建议 true
enableRobotsTXT: true # 允许爬虫抓取到搜索引擎，建议 true

hasCJKLanguage: true # 自动检测是否包含 中文日文韩文 如果文章中使用了很多中文引号的话可以开启

buildDrafts: false
buildFuture: false
buildExpired: false

#googleAnalytics: UA-123-45 # 谷歌统计
# Copyright: Sulv

paginate: 15    # 首页每页显示的文章数

minify:
    disableXML: true
    # minifyOutput: true

permalinks:
  post: "/:title/"
  # post: "/:year/:month/:day/:title/"

defaultContentLanguage: en # 最顶部首先展示的语言页面
defaultContentLanguageInSubdir: true

languages:
    en:
      languageName: "English"
      # contentDir: content/english
      weight: 1
      profileMode:
        enabled: true
        title: (〃'▽'〃)
        subtitle: "🧨一个简朴、持续更新的博客<br/>👏🏼欢迎光临<b>小任同学</b>的博客<br/>👇联系方式 😆"
        imageUrl: "img/icon-512.png"
        imageTitle: 
        imageWidth: 150
        imageHeight: 150
        buttons:
          - name: 📋 文章
            url: /posts/blog
          - name: 🏡 生活
            url: /posts/life
          - name: 📕 阅读
            url: /posts/read
          # - name: 大佬的博客
          #   url: https://www.xyming108.top
      menu:
        main:
          
          - identifier: home
            name: 🏠主页
            url: /
            weight: 2
          - identifier: posts
            name: 📚文章
            url: posts
            weight: 3
          - identifier: archives
            name: ⏱时间轴
            url: archives/
            weight: 20
          #- identifier: search
          #  name: 🔍搜索
          #  url: search
          #  weight: 1
          - identifier: tags
            name: 🔖标签
            url: tags
            weight: 40
          - identifier: about
            name: 🙋🏻‍♂️关于
            url: about
            weight: 50
          - identifier: links
            name: 🤝友链
            url: links
            weight: 60

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    # description: "这是一个纯粹的博客......"
    mainSections:
        - posts
    author: 小任同学
    # author: ["Me", "You"] # multiple authors

    description: "一个不两极分化的博客"
  
    defaultTheme: auto  # defaultTheme: light or  dark 
    disableThemeToggle: false
    DateFormat: "2006-01-02"
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecialistPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    hideFooter: false # 隐藏页脚
    ShowWordCounts: true
    VisitCount: true
    ShowLastMod: true #显示文章更新时间

    ShowToc: true # 显示目录
    TocOpen: true # 自动展开目录

    comments: true
    
    socialIcons:
        - name: github
          url: "https://github.com/coderRenxy"
        #- name: twitter
        #  url:  "img/twitter.png"
        - name: facebook
          url: "https://www.facebook.com/profile.php?id=100078348180825"
        - name: Telegramcd 。。
          url: "https://t.me/RenCigarette"
        - name: QQ
          url: "img/qq.jpg"
        - name: WeChat
          url: "img/wechat.jpg"
        # - name: Phone
        #   url: "img/phone.png"
        - name: email
          url: "mailto:1074136734@qq.com"
        - name: RSS
          url: "index.xml"

    

    label:
    #     text: "小任同学's Blog"
         icon: img/icon-32.png
    #     iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    assets:
        #favicon: "img/icon-512.png"
        favicon: "img/icon-512.png"
        favicon16x16: "img/icon-512.png"
        favicon32x32: "icon-512.png"
        apple_touch_icon: "icon-512.png"
        safari_pinned_tab: "icon-512.png"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page
    
    utteranc:
        enable: true
        repo: "coderRenxy/coderrenxy.github.io"    # The repo to store comments
        issueTerm: "title"
        theme: "github-light"
    
    editPost:
        URL: "https://github.com/coderRenxy/coderrenxy.github.io/content"
        Text: "🖍️修改" # edit text
        appendFilePath: true # to append file path to Edit link

    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 1
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary"]

    #twikoo:
      #version: 1.4.11
    
taxonomies:
    category: categories
    tag: tags
    series: series

markup:
    goldmark:
        renderer:
            unsafe: true # HUGO 默认转义 Markdown 文件中的 HTML 代码，如需开启的话
    highlight:
        # anchorLineNos: true
        codeFences: true  
        guessSyntax: true
        lineNos: true
        # noClasses: false
        style: solarized-dark256 
        # style: darcula

        # codeFences：代码围栏功能，这个功能一般都要设为 true 的，不然很难看，就是干巴巴的-代码文字，没有颜色。
        # guessSyntax：猜测语法，这个功能建议设置为 true, 如果你没有设置要显示的语言则会自动匹配。
        # hl_Lines：高亮的行号，一般这个不设置，因为每个代码块我们可能希望让高亮的地方不一样。
        # lineNoStart：行号从编号几开始，一般从 1 开始。
        # lineNos：是否显示行号，我比较喜欢显示，所以我设置的为 true.
        # lineNumbersInTable：使用表来格式化行号和代码,而不是 标签。这个属性一般设置为 true.
        # noClasses：使用 class 标签，而不是内嵌的内联样式

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
        
